matrix:
  include:
    # - stage: "Lint"
    #   language: node_js
    #   os: linux
    #   node_js: "6"
    #   jdk: oraclejdk8
    #   script: npm run ci.tslint
    - stage: "WebPack"
      os: osx
      env:
        - Platform="iOS"
      osx_image: xcode8.3
      language: node_js 
      node_js: "6"
      jdk: oraclejdk8
      script: npm run build && cd ../demo && npm i && npm run build-ios-bundle && cd ../demo-angular && npm i && npm run build-ios-bundle
    - language: android
      os: linux
      env:
        - Platform="Android"
      jdk: oraclejdk8
      before_install: nvm install 6.10.3
      script: cd ../src && npm run build && cd ../demo && npm i && npm run build-android-bundle && cd ../demo-angular && npm i && npm run build-android-bundle
    - stage: "Build"
      env: 
        - Android="23"
      language: android
      os: linux
      jdk: oraclejdk8
      before_install: cd src && nvm install 6.10.3
      script: npm run ci.android
    - os: osx
      env: 
        - iOS="10.3"
        - Xcode="8.3"
      osx_image: xcode8.3
      language: node_js 
      node_js: "6"
      jdk: oraclejdk8
      script: npm run ci.ios

android:
  components:
    - tools
    - platform-tools
    - build-tools-23.0.1
    - android-23
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-23

before_cache:
    - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
    directories:
        - .nvm
        - $HOME/.gradle/caches/
        - $HOME/.gradle/wrapper/

before_install:
    - cd src

install:
    - npm install -g nativescript
    - npm install -g tslint
    - npm install -g typescript@2.2.2
    - tns usage-reporting disable
    - tns error-reporting disable
    - npm install